# We're using version 3.7 of the Docker Compose file format
version: "3.7"

# Define services/containers
services:
  #Postgres
  postgres:
    image: postgres:latest
    container_name: ${BASE_NAME}-postgres
    env_file: .env_postgres
    networks:
      - pg_network
    ports:
      - "5435:5432"
    volumes:
      - ${POSTGRES_DATA_VOLUME}:/data/postgres
    restart: unless-stopped
  #pgadmin for postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: ${BASE_NAME}-pgadmin
    env_file: .env_postgres
    networks:
      - pg_network
    ports:
      - "8082:80"
    volumes:
      - ${PGADMIN_DATA}:/root/.pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

# Define networks
networks:
  #my-network:
  pg_network:
    driver: bridge
volumes:
  postgres:
  pgadmin:
